"""
URL configuration for payment_gateway project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.http import FileResponse
import os

def test_page(request):
    """Serve the test HTML page"""
    file_path = os.path.join(settings.BASE_DIR, 'static', 'test.html')
    return FileResponse(open(file_path, 'rb'), content_type='text/html')

urlpatterns = [
    path('', test_page, name='test_page'),
    path('admin/', admin.site.urls),
    
    # API endpoints with versioning (no namespace)
    path('api/v1/payments/', include('payments.urls')),
]

# Serve static files during development
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
